version: '2.2'
services:
  db_accounts:
    image:          postgres:11
    container_name: db_accounts
    restart:        always
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       accounts_db
      PGDATA:            /var/lib/postgresql/data/pgdata
    ports:
      - '5431:5432'
    volumes:
      - ./postgres/accounts_db:/var/lib/postgresql/data
  db_message:
    image:          postgres:11
    container_name: db_message
    restart:        always
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       message_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/message_db:/var/lib/postgresql/data
  db_abuse:
    image:          postgres:11
    container_name: db_abuse
    restart:        always
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       abuse_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
    volumes:
      - ./postgres/abuse_db:/var/lib/postgresql/data

  redis_master:
    image: redis:5
    container_name: redis_master
    restart:        always
    ports:
      - '6379:6379'
    volumes:
      - ./redis/redis_master:/data
  redis_slave:
    image: redis:5
    container_name: redis_slave
    restart:        always
    command: redis-server --port 6380 --slaveof redis_master 6379
    ports:
      - '6380:6380'
    volumes:
      - ./redis/redis_slave:/data
  sentinel:
    build: ./sentinel
    container_name: redis_sentinel
    restart:        always
    ports:
      - '26379:26379'
    environment:
      - SENTINEL_NAME=mysentinel
      - HOST_IP=127.0.0.1
    volumes:
      - ./redis/redis_slave:/data
